[package]
name = "git-rsl"
version = "0.1.0"
authors = ["Jeff Weiss <jweiss@polysync.io>"]

[dependencies]
clap = "2"
git2 = "0.6"
gpgme = "0.6"
lazy_static = "0.2"
rand = "0.3"
regex = "0.2"
rust-crypto = "0.2"
